scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['insurance-claim-processor:8080']
  - job_name: 'rabbitmq'
    scrape_interval: 5s
    metrics_path: /metrics/per-object
    static_configs:
      - targets: ['rabbitmq:15692']
